# Generated by Django 4.2.13 on 2024-07-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='emp_name')),
                ('email', models.EmailField(max_length=300, verbose_name='emp_email')),
                ('age', models.IntegerField(verbose_name='emp_age')),
                ('job_name', models.CharField(max_length=150, verbose_name='emp_position')),
                ('phone', models.CharField(max_length=13, verbose_name='emp_phone')),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='proj_name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='proj_desc')),
                ('start_date', models.DateField(verbose_name='proj_start')),
                ('end_date', models.DateField(verbose_name='proj_deadline')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20, verbose_name='proj_status')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='task_name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='task_desc')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20, verbose_name='task_status')),
                ('due_date', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.project', verbose_name='task_project')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='dep_name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='dep_desc')),
                ('employees', models.ManyToManyField(related_name='departments', to='api.employee')),
            ],
        ),
    ]
