# Generated by Django 4.2.13 on 2024-07-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_department_employees_employee_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='employees',
            new_name='department',
        ),
    ]
