# Generated by Django 4.2.13 on 2024-07-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_assigned_to_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project', verbose_name='task_project'),
        ),
    ]
