# Generated by Django 4.2.13 on 2024-07-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_task_assigned_to_name_alter_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='expense_name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='expense_desc')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('Pending', 'Pending'), ('NotApproved', 'NotApproved')], default='Pending', max_length=20, verbose_name='expense_status')),
                ('due_date', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='api.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='api.project', verbose_name='expense_project')),
            ],
        ),
    ]
